#!/bin/sh
### Start service information
# Provides: Go based service
# Description: Script to control the execution of a Go-based application.
# version="1.0"
### End service information

name="xray-xkeen-metrics"
go_app="/opt/sbin/$name"
pid_file="/var/run/$name.pid"

go_app_status() {
    if [ -f "$pid_file" ]; then
        if kill -0 $(cat "$pid_file") 2> /dev/null; then
            return 0
        else
            rm -f "$pid_file"
            return 1
        fi
    else
        return 1
    fi
}

start() {
    if go_app_status; then
        echo -e "  $name application is already running"
    else
        echo "Starting $name application..."
        if [ -f "$config_file" ]; then
            echo "Using configuration file: $config_file"
            $go_app -config "$config_file" &
        else
            echo "Configuration file not found. Using environment variables."
            LOG_FILE_PATH="/opt/var/log/xray/access.log"
            AUTH_TOKEN="qwerty12345"
            export LOG_FILE_PATH
            export AUTH_TOKEN
            $go_app &
        fi
        echo $! > "$pid_file"
        echo -e "  $name application started (PID: $(cat $pid_file))"
    fi
}

stop() {
    if go_app_status; then
        echo "Stopping $name application..."
        kill -9 "$(cat "$pid_file")"
        rm -f "$pid_file"
        echo -e "  $name application stopped"
    else
        echo -e "  $name application is not running"
    fi
}

restart() {
    stop > /dev/null 2>&1
    start > /dev/null 2>&1
    echo -e "  $name application restarted"
}

case "$1" in
    start)
        start;;
    stop)
        stop;;
    restart)
        restart;;
    status)
        if go_app_status; then
            echo -e "  $name application is running (PID: $(cat $pid_file))"
        else
            echo -e "  $name application is not running"
        fi;;
    *)
        echo -e "  Usage: start | stop | restart | status";;
esac
exit 0
